[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Windowed"
opacity = 0.8

[window.padding]
x = 10
y = 10

[scrolling]
history = 1000
multiplier = 3

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[selection]
save_to_clipboard = true
